### ISSUE TITLE
Card error using avatar icon

### ISSUE THREAD

**Issue by fjfeijoo** [Ullfis/aurelia-mdc-bridge#12]
When I use this code in a view:

```
  <style>
    .my-avatar3 {
      margin-top: 0.8rem;
    }
  </style>

  <mdc-card>
    <mdc-card-title title="Title">
      <i class="material-icons md-36 my-avatar3">face</i>
    </mdc-card-title>
  </mdc-card>
```

I'm getting an error like this:
```
Unhandled rejection TypeError: Cannot set property 'position' of undefined
    at MdcCardTitle.attached (http://localhost:9000/scripts/mdc-bundle.js:42792:50)
    at Controller.attached (http://localhost:9000/scripts/vendor-bundle.js:22813:24)
    at View.attached (http://localhost:9000/scripts/vendor-bundle.js:20878:24)
    at ViewSlot.add (http://localhost:9000/scripts/vendor-bundle.js:21041:14)
    at http://localhost:9000/scripts/vendor-bundle.js:26793:43`
```
Looking at the 'attached' member in card-title.ts:

```
private attached() {
    if (!this.isAvatar) {
      const avatarElement = this.elementPrimary.firstChild as HTMLElement;
      if (avatarElement) {
        avatarElement.style.position = 'absolute';
      }
      this.elementPrimary.classList.add('mdc-mdc-card-avatar');
    }
    this.titleChanged(this.title);
    this.subtitleChanged(this.subtitle);
    this.largeChanged(this.large);
  }

```

Looks like avatarElement (the 'i') doesn't have a 'style' property and then fails.

I have checked your sample code and it's working fine so I have no idea why it fails in my case.

Any ideas?

Thanks!

**Comment by Ullfis** [comment]
I also got that error. I will take a look at it tomorrow.
