### ISSUE TITLE
Allow slots for dialog boxes

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#27]
I need to customize the contents of the header, body, and footer of my dialog box. Just like `mdc-list-item` supports slots for it's various locations, it would be great if there could be slots for the dialog box as well.

Something like...
```
<span slot="header"></span>
<span slot="body"></span>
<span slot="footer"></span>
```

**Comment by Ullfis** [comment]
```
<span slot="body"></span>
```
..is not needed. This is default slot.

```html
<mdc-dialog>
  body
</mdc-dialog>
```

I can add slot around header and footer content so it can be replaced if slot is used:

Source:
```jade
      // HEADER
      header.mdc-dialog__header(show.bind="header.length !== 0")
        slot(name="header")
          h2.mdc-dialog__header__title(id="${controlId}-label") ${header}

      .

      // FOOTER
      footer.mdc-dialog__footer
        slot(name="footer")
          button.mdc-button.mdc-dialog__footer__button.mdc-dialog__footer__button--cancel(type="button" ref="cancelButtonElement") ${cancel}
          button.mdc-button.mdc-dialog__footer__button.mdc-dialog__footer__button--accept(type="button" ref="acceptButtonElement" disabled.bind="acceptDisabled") ${accept}
```

You can test it with:

```batch
npm install github:ullfis/aurelia-mdc-bridge#ds-test
```

**Comment by djensen47** [comment]
Awesome, I'll take a look at it Tuesday afternoon, PST.

**Comment by djensen47** [comment]
Oops, I completely forgot about this. Sorry. I'll give it a try soon.

**Comment by djensen47** [comment]
It didn't seem to work. The dialog seems to lose some of it's styling and then I get this error:

```
Unhandled rejection TypeError: Cannot read property 'classList' of undefined
    at MdcDialog.acceptActionChanged (http://localhost:9000/scripts/mdc-bundle.js:43564:38)
    at MdcDialog.attached (http://localhost:9000/scripts/mdc-bundle.js:43542:18)
    at Controller.attached (http://localhost:9000/scripts/vendor-bundle.js:22606:24)
    at View.attached (http://localhost:9000/scripts/vendor-bundle.js:20665:24)
    at Controller.attached (http://localhost:9000/scripts/vendor-bundle.js:22610:19)
    at View.attached (http://localhost:9000/scripts/vendor-bundle.js:20665:24)
    at ViewSlot.attached (http://localhost:9000/scripts/vendor-bundle.js:21023:15)
    at View.attached (http://localhost:9000/scripts/vendor-bundle.js:20670:21)
    at ViewSlot.attached (http://localhost:9000/scripts/vendor-bundle.js:21023:15)
    at http://localhost:9000/scripts/vendor-bundle.js:13232:30
From previous event:
    at Aurelia.setRoot (http://localhost:9000/scripts/vendor-bundle.js:13230:42)
    at http://localhost:9000/scripts/app-bundle.js:319:22
From previous event:
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:318:35)
    at http://localhost:9000/scripts/vendor-bundle.js:12059:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:12054:56)
    at http://localhost:9000/scripts/vendor-bundle.js:12090:14
From previous event:
    at bootstrap (http://localhost:9000/scripts/vendor-bundle.js:12089:26)
    at http://localhost:9000/scripts/vendor-bundle.js:12076:9
    at <anonymous>
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:12071:61)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:12096:37)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5484:33)
    at Module.check (http://localhost:9000/scripts/vendor-bundle.js:4671:51)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4964:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5345:39)
    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4949:33)
    at http://localhost:9000/scripts/vendor-bundle.js:3922:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:3847:31)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4901:17)
    at Module.init (http://localhost:9000/scripts/vendor-bundle.js:4576:26)
    at http://localhost:9000/scripts/vendor-bundle.js:5248:36
```

**Comment by Ullfis** [comment]
Another try on `ds-test` branch.

```
npm install github:ullfis/aurelia-mdc-bridge#ds-test
```
code branch: `dialog-slots`
build branch: `ds-test`

Example added

**Comment by djensen47** [comment]
It's mostly working.

This will not show the header:
```html
  <mdc-dialog view-model.ref="dialog">
    <span slot="header">This is a header</span>
    <span slot="footer">Footer</span>
    Body
  </mdc-dialog>
```

However, this *will* show the header:
```html
  <mdc-dialog view-model.ref="dialog" header="a">
    <span slot="header">This is a header</span>
    <span slot="footer">Footer</span>
    Body
  </mdc-dialog>
```

**Comment by Ullfis** [comment]
```
npm install github:ullfis/aurelia-mdc-bridge#ds-test
```

**Comment by djensen47** [comment]
Thanks. I'll try it out tonight.

**Comment by djensen47** [comment]
Just tested it and it works! Thanks.
